//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ComputingCluster.cpp
//  @ Date : 20.05.2021
//  @ Author : 
//
//


#include "ComputingCluster.h"

ComputingCluster::ComputingCluster() {

}

void ComputingCluster::addComputer(IComputingDevice* computer) {

}

