//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Computer.h
//  @ Date : 20.05.2021
//  @ Author : 
//
//


#if !defined(_COMPUTER_H)
#define _COMPUTER_H

#include "IComputingDevice.h"

class Computer : public IComputingDevice {
public:
	Computer(int computingPower);
private:
	int computingPower;
};

#endif  //_COMPUTER_H
