//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ComputingCluster.h
//  @ Date : 20.05.2021
//  @ Author : 
//
//


#if !defined(_COMPUTINGCLUSTER_H)
#define _COMPUTINGCLUSTER_H

#include "IComputingDevice.h"

class ComputingCluster : public IComputingDevice {
public:
	ComputingCluster();
	void addComputer(IComputingDevice* computer);
private:
	vector<IComputingDevice*> computers;
};

#endif  //_COMPUTINGCLUSTER_H
