//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Computer.cpp
//  @ Date : 20.05.2021
//  @ Author : 
//
//


#include "Computer.h"

Computer::Computer(int computingPower) {

}

