//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IComputingDevice.h
//  @ Date : 20.05.2021
//  @ Author : 
//
//


#if !defined(_ICOMPUTINGDEVICE_H)
#define _ICOMPUTINGDEVICE_H


class IComputingDevice {
public:
	virtual void computeSomething() = 0;
};

#endif  //_ICOMPUTINGDEVICE_H
